// Generated by CoffeeScript 2.7.0
(function() {
  var A;

  A = class A {
    constructor() {
      this.a = 1;
    }

    b() {
      return this.a = 2;
    }

    c() {
      return this.a = 3;
    }

  };

  console.log(new A().a);

}).call(this);
